### ISSUE TITLE
Skill ContextMenu not working in v11, and errors when creating it in activateListeners on NPC and Creature sheets

### ISSUE THREAD

**Issue by Muttley** [superseva/fallout#63]
```javascript
foundry.js:753 TypeError: An error occurred while rendering FalloutActorSheet 35. Cannot read properties of undefined (reading 'addEventListener')
    at ContextMenu.bind (foundry.js:63844:13)
    at new ContextMenu (foundry.js:63799:10)
    at FalloutActorSheet.activateListeners (actor-sheet.mjs:382:5)
    at FalloutActorSheet._render (foundry.js:5756:10)
    at async FalloutActorSheet._render (foundry.js:6444:5)
onError @ foundry.js:753
(anonymous) @ foundry.js:5685
Promise.catch (async)
render @ foundry.js:5683
render @ foundry.js:7023
_onClickEntryName @ foundry.js:69173
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

**Comment by superseva** [comment]
yeah, I fixed that in other game so I will add the fix to Fallout. I just need to finish updating official MYZ modules first

**Comment by superseva** [comment]
fixed
